name: ML Pipeline with DVC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up DVC
        run: |
          pip install dvc 
          dvc pull 
          ls -lh data/raw  

      - name: Run ML Pipeline
        run: |
          python src/data_processing.py
          python src/model_training.py
          python src/evaluate_model.py

      - name: Commit and Push DVC Metadata
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          dvc add data/processed/iris_cleaned.csv
          git add data/processed/iris_cleaned.csv.dvc
          git commit -m "Update processed data"
          git push
          dvc push 
